#ifndef _MapTexDef_H_
#define _MapTexDef_H_

enum MapTexID
{
	MT_BARRIER_1	= 0,
	MT_BARRIER_2	= 1,
	MT_BARRIER_3	= 2,
	MT_BARRIER_4	= 3,

	MT_BUILD_DOOR_1	= 4,
	MT_BUILD_DOOR_2	= 5,

	MT_BUILD_ICON_1	= 6,
	MT_BUILD_ICON_2	= 7,
	MT_BUILD_ICON_3 = 8,
	MT_BUILD_ICON_4 = 9,
	MT_BUILD_ICON_5 = 10,
	MT_BUILD_ICON_6 = 11,

	MT_BUILD_TOP_1	= 12,
	MT_BUILD_TOP_2	= 13,
	MT_BUILD_TOP_3	= 14,
	MT_BUILD_TOP_4	= 15,
	MT_BUILD_TOP_5	= 16,
	MT_BUILD_TOP_6	= 17,
	MT_BUILD_TOP_7	= 18,
	MT_BUILD_TOP_8	= 19,

	MT_EMPTY		= 20,

	MT_CAVE_1		= 21,
	MT_CAVE_2		= 22,
	MT_CAVE_3		= 23,
	MT_CAVE_4		= 24,
	MT_CAVE_5		= 25,
	MT_CAVE_6		= 26,
	MT_CAVE_7		= 27,
	MT_CAVE_8		= 28,
	MT_CAVE_9		= 29,
	MT_CAVE_10		= 30,
	MT_CAVE_11		= 31,
	MT_CAVE_12		= 32,
	MT_CAVE_13		= 33,
	MT_CAVE_14		= 34,
	MT_CAVE_15		= 35,
	MT_CAVE_16		= 36,
	MT_CAVE_17		= 37,
	MT_CAVE_18		= 38,
	MT_CAVE_19		= 39,
	MT_CAVE_20		= 40,
	MT_CAVE_21		= 41,
	MT_CAVE_22		= 42,
	MT_CAVE_23		= 43,
	MT_CAVE_24		= 44,
	MT_CAVE_25		= 45,
	MT_CAVE_26		= 46,
	MT_CAVE_27		= 47,
	MT_CAVE_28		= 48,
	MT_CAVE_29		= 49,
	MT_CAVE_30		= 50,
	MT_CAVE_31		= 51,
	MT_CAVE_32		= 52,
	MT_CAVE_33		= 53,
	MT_CAVE_34		= 54,
	MT_CAVE_35		= 55,
	MT_CAVE_36		= 56,
	MT_CAVE_37		= 57,
	MT_CAVE_38		= 58,
	MT_CAVE_39		= 59,
	MT_CAVE_40		= 60,
	MT_CAVE_41		= 61,
	MT_CAVE_42		= 62,
	MT_CAVE_43		= 63,
	MT_CAVE_44		= 64,
	MT_CAVE_45		= 65,
	MT_CAVE_46		= 66,
	MT_CAVE_47		= 67,
	MT_CAVE_48		= 68,
	MT_CAVE_49		= 69,
	MT_CAVE_50		= 70,
	MT_CAVE_51		= 71,
	MT_CAVE_52		= 72,
	MT_CAVE_53		= 73,
	MT_CAVE_54		= 74,
	MT_CAVE_55		= 75,
	MT_CAVE_56		= 76,
	MT_CAVE_57		= 77,

	MT_CLIF_1		= 78,
	MT_CLIF_2		= 79,
	MT_CLIF_3		= 80,

	MT_FLOOR_1		= 81,
	MT_FLOOR_2		= 82,
	MT_FLOOR_3		= 83,
	MT_FLOOR_4		= 84,
	MT_FLOOR_5		= 85,
	MT_FLOOR_6		= 86,
	MT_FLOOR_7		= 87,
	MT_FLOOR_8		= 88,
	MT_FLOOR_9		= 89,
	MT_FLOOR_10		= 90,
	MT_FLOOR_11		= 91,
	MT_FLOOR_12		= 92,
	MT_FLOOR_13		= 93,
	MT_FLOOR_14		= 94,
	MT_FLOOR_15		= 95,
	MT_FLOOR_16		= 96,
	MT_FLOOR_17		= 97,
	MT_FLOOR_18		= 98,
	MT_FLOOR_19		= 99,
	MT_FLOOR_20		= 100,
	MT_FLOOR_21		= 101,
	MT_FLOOR_22		= 102,
	MT_FLOOR_23		= 103,
	MT_FLOOR_24		= 104,
	MT_FLOOR_25		= 105,

	MT_GRASS_1		= 106,
	MT_GRASS_2		= 107,
	MT_GRASS_3		= 108,
	MT_GRASS_4		= 109,
	MT_GRASS_5		= 110,

	MT_MAC_1		= 111,
	MT_MAC_2		= 112,
	MT_MAC_3		= 113,
	MT_MAC_4		= 114,
	MT_MAC_5		= 115,
	MT_MAC_6		= 116,
	MT_MAC_7		= 117,
	MT_MAC_8		= 118,
	MT_MAC_9		= 119,
	MT_MAC_10		= 120,
	MT_MAC_11		= 121,
	MT_MAC_12		= 122,
	MT_MAC_13		= 123,
	MT_MAC_14		= 124,
	MT_MAC_15		= 125,

	MT_MAP_1		= 126,
	MT_MAP_2		= 127,
	MT_MAP_3		= 128,
	MT_MAP_4		= 129,
	MT_MAP_5		= 130,
	MT_MAP_6		= 131,
	MT_MAP_7		= 132,
	MT_MAP_8		= 133,
	MT_MAP_9		= 134,
	MT_MAP_10		= 135,
	MT_MAP_11		= 136,
	MT_MAP_12		= 137,
	MT_MAP_13		= 138,
	MT_MAP_14		= 139,
	MT_MAP_15		= 140,
	MT_MAP_16		= 141,
	MT_MAP_17		= 142,
	MT_MAP_18		= 143,
	MT_MAP_19		= 144,
	MT_MAP_20		= 145,
	MT_MAP_21		= 146,

	MT_ROCK_1		= 147,
	MT_ROCK_2		= 148,

	MT_SAND_1		= 149,
	MT_SAND_2		= 150,
	MT_SAND_3		= 151,
	MT_SAND_4		= 152,

	MT_SKY_1		= 153,
	MT_SKY_2		= 154,

	MT_TREE_1		= 155,
	MT_TREE_2		= 156,

	MT_WALL_1		= 157,
	MT_WALL_2		= 158,
	MT_WALL_3		= 159,
	MT_WALL_4		= 160,
	MT_WALL_5		= 161,
	MT_WALL_6		= 162,
	MT_WALL_7		= 163,
	MT_WALL_8		= 164,
	MT_WALL_9		= 165,
	MT_WALL_10		= 166,
	MT_WALL_11		= 167,
	MT_WALL_12		= 168,
	MT_WALL_13		= 169,
	MT_WALL_14		= 160,
	MT_WALL_15		= 171,
	MT_WALL_16		= 172,
	MT_WALL_17		= 173,
	MT_WALL_18		= 174,
	MT_WALL_19		= 175,
	MT_WALL_20		= 176,
	MT_WALL_21		= 177,
	MT_WALL_22		= 178,
	MT_WALL_23		= 179,
	MT_WALL_24		= 180,
	MT_WALL_25		= 181,
	MT_WALL_26		= 182,
	MT_WALL_27		= 183,
	MT_WALL_28		= 184,
	MT_WALL_29		= 185,
	MT_WALL_30		= 186,
	MT_WALL_31		= 187,
	MT_WALL_32		= 188,
	MT_WALL_33		= 189,
	MT_WALL_34		= 190,
	MT_WALL_35		= 191,
	MT_WALL_36		= 192,
	MT_WALL_37		= 193,
	MT_WALL_38		= 194,
	MT_WALL_39		= 195,
	MT_WALL_40		= 196,
	MT_WALL_41		= 197,
	MT_WALL_42		= 198,
	MT_WALL_43		= 199,
	MT_WALL_44		= 200,
	MT_WALL_45		= 201,
	MT_WALL_46		= 202,
	MT_WALL_47		= 203,
	MT_WALL_48		= 204,
	MT_WALL_49		= 205,
	MT_WALL_50		= 206,
	MT_WALL_51		= 207,
	MT_WALL_52		= 208,
	MT_WALL_53		= 209,
	MT_WALL_54		= 210,
	MT_WALL_55		= 211,
	MT_WALL_56		= 212,
	MT_WALL_57		= 213,
	MT_WALL_58		= 214,
	MT_WALL_59		= 215,
	MT_WALL_60		= 216,
	MT_WALL_61		= 217,
	MT_WALL_62		= 218,
	MT_WALL_63		= 219,
	MT_WALL_64		= 220,
	MT_WALL_65		= 221,
	MT_WALL_66		= 222,
	MT_WALL_67		= 223,
	MT_WALL_68		= 224,
	MT_WALL_69		= 225,
	MT_WALL_70		= 226,
	MT_WALL_71		= 227,
	MT_WALL_72		= 228,
	MT_WALL_73		= 229,
	MT_WALL_74		= 230,
	MT_WALL_75		= 231,
	MT_WALL_76		= 232,
	MT_WALL_77		= 233,
	MT_WALL_78		= 234,
	MT_WALL_79		= 235,
	MT_WALL_80		= 236,
	MT_WALL_81		= 237,
	MT_WALL_82		= 238,
	MT_WALL_83		= 239,
	MT_WALL_84		= 240,
	MT_WALL_85		= 241,
	MT_WALL_86		= 242,
	MT_WALL_87		= 243,
	MT_WALL_88		= 244,

	MT_WATER_1		= 245,
	MT_WATER_2		= 246,

	MT_APPEND_1		= 247,
	MT_APPEND_2		= 248,
	MT_APPEND_3		= 249,
	MT_APPEND_4		= 250,

	MT_MAX
};

struct MapTexInfo
{
	const char* texName;
	bool actorMovable;
	bool tankMovable;
};

// To Do: optimize
static const MapTexInfo sMapTexInfos[MT_MAX] = 
{
	{"../Texture/MapTiles/Barrier_1.png", false, false},
	{"../Texture/MapTiles/Barrier_2.png", false, false},
	{"../Texture/MapTiles/Barrier_3.png", false, false},
	{"../Texture/MapTiles/Barrier_4.png", true, false},

	{"../Texture/MapTiles/Build_Door_1.png", true, true},
	{"../Texture/MapTiles/Build_Door_2.png", true, true},

	{"../Texture/MapTiles/Build_Icon_1.png", false, false},
	{"../Texture/MapTiles/Build_Icon_2.png", false, false},
	{"../Texture/MapTiles/Build_Icon_3.png", false, false},
	{"../Texture/MapTiles/Build_Icon_4.png", false, false},
	{"../Texture/MapTiles/Build_Icon_5.png", false, false},
	{"../Texture/MapTiles/Build_Icon_6.png", false, false},

	{"../Texture/MapTiles/Build_Top_1.png", false, false},
	{"../Texture/MapTiles/Build_Top_2.png", false, false},
	{"../Texture/MapTiles/Build_Top_3.png", false, false},
	{"../Texture/MapTiles/Build_Top_4.png", false, false},
	{"../Texture/MapTiles/Build_Top_5.png", false, false},
	{"../Texture/MapTiles/Build_Top_6.png", false, false},
	{"../Texture/MapTiles/Build_Top_7.png", false, false},
	{"../Texture/MapTiles/Build_Top_8.png", false, false},

	{"../Texture/MapTiles/Empty.png", true, true},

	{"../Texture/MapTiles/Cave_1.png", true, false},
	{"../Texture/MapTiles/Cave_2.png", false, false},
	{"../Texture/MapTiles/Cave_3.png", true, true},
	{"../Texture/MapTiles/Cave_4.png", false, false},
	{"../Texture/MapTiles/Cave_5.png", false, false},
	{"../Texture/MapTiles/Cave_6.png", true, true},
	{"../Texture/MapTiles/Cave_7.png", false, false},
	{"../Texture/MapTiles/Cave_8.png", false, false},
	{"../Texture/MapTiles/Cave_9.png", false, false},
	{"../Texture/MapTiles/Cave_10.png", false, false},
	{"../Texture/MapTiles/Cave_11.png", false, false},
	{"../Texture/MapTiles/Cave_12.png", false, false},
	{"../Texture/MapTiles/Cave_13.png", false, false},
	{"../Texture/MapTiles/Cave_14.png", false, false},
	{"../Texture/MapTiles/Cave_15.png", false, false},
	{"../Texture/MapTiles/Cave_16.png", false, false},
	{"../Texture/MapTiles/Cave_17.png", false, false},
	{"../Texture/MapTiles/Cave_18.png", false, false},
	{"../Texture/MapTiles/Cave_19.png", false, false},
	{"../Texture/MapTiles/Cave_20.png", false, false},
	{"../Texture/MapTiles/Cave_21.png", false, false},
	{"../Texture/MapTiles/Cave_22.png", false, false},
	{"../Texture/MapTiles/Cave_23.png", true, true},
	{"../Texture/MapTiles/Cave_24.png", false, false},
	{"../Texture/MapTiles/Cave_25.png", false, false},
	{"../Texture/MapTiles/Cave_26.png", false, false},
	{"../Texture/MapTiles/Cave_27.png", false, false},
	{"../Texture/MapTiles/Cave_28.png", false, false},
	{"../Texture/MapTiles/Cave_29.png", false, false},
	{"../Texture/MapTiles/Cave_30.png", false, false},
	{"../Texture/MapTiles/Cave_31.png", false, false},
	{"../Texture/MapTiles/Cave_32.png", false, false},
	{"../Texture/MapTiles/Cave_33.png", false, false},
	{"../Texture/MapTiles/Cave_34.png", false, false},
	{"../Texture/MapTiles/Cave_35.png", false, false},
	{"../Texture/MapTiles/Cave_36.png", false, false},
	{"../Texture/MapTiles/Cave_37.png", false, false},
	{"../Texture/MapTiles/Cave_38.png", false, false},
	{"../Texture/MapTiles/Cave_39.png", false, false},
	{"../Texture/MapTiles/Cave_40.png", true, true},
	{"../Texture/MapTiles/Cave_41.png", true, false},
	{"../Texture/MapTiles/Cave_42.png", true, true},
	{"../Texture/MapTiles/Cave_43.png", false, false},
	{"../Texture/MapTiles/Cave_44.png", false, false},
	{"../Texture/MapTiles/Cave_45.png", false, false},
	{"../Texture/MapTiles/Cave_46.png", true, true},
	{"../Texture/MapTiles/Cave_47.png", false, false},
	{"../Texture/MapTiles/Cave_48.png", true, true},
	{"../Texture/MapTiles/Cave_49.png", false, false},
	{"../Texture/MapTiles/Cave_50.png", false, false},
	{"../Texture/MapTiles/Cave_51.png", false, false},
	{"../Texture/MapTiles/Cave_52.png", false, false},
	{"../Texture/MapTiles/Cave_53.png", false, false},
	{"../Texture/MapTiles/Cave_54.png", false, false},
	{"../Texture/MapTiles/Cave_55.png", false, false},
	{"../Texture/MapTiles/Cave_56.png", true, false},
	{"../Texture/MapTiles/Cave_57.png", false, false},

	{"../Texture/MapTiles/Clif_1.png", false, false},
	{"../Texture/MapTiles/Clif_2.png", false, false},
	{"../Texture/MapTiles/Clif_3.png", false, false},

	{"../Texture/MapTiles/Floor_1.png", true, true},
	{"../Texture/MapTiles/Floor_2.png", true, true},
	{"../Texture/MapTiles/Floor_3.png", true, true},
	{"../Texture/MapTiles/Floor_4.png", true, false},
	{"../Texture/MapTiles/Floor_5.png", true, false},
	{"../Texture/MapTiles/Floor_6.png", true, true},
	{"../Texture/MapTiles/Floor_7.png", true, false},
	{"../Texture/MapTiles/Floor_8.png", false, false},
	{"../Texture/MapTiles/Floor_9.png", true, false},
	{"../Texture/MapTiles/Floor_10.png", true, true},
	{"../Texture/MapTiles/Floor_11.png", true, false},
	{"../Texture/MapTiles/Floor_12.png", false, false},
	{"../Texture/MapTiles/Floor_13.png", false, false},
	{"../Texture/MapTiles/Floor_14.png", true, true},
	{"../Texture/MapTiles/Floor_15.png", true, false},
	{"../Texture/MapTiles/Floor_16.png", true, false},
	{"../Texture/MapTiles/Floor_17.png", true, true},
	{"../Texture/MapTiles/Floor_18.png", true, true},
	{"../Texture/MapTiles/Floor_19.png", false, false},
	{"../Texture/MapTiles/Floor_20.png", false, false},
	{"../Texture/MapTiles/Floor_21.png", true, false},
	{"../Texture/MapTiles/Floor_22.png", true, true},
	{"../Texture/MapTiles/Floor_23.png", true, true},
	{"../Texture/MapTiles/Floor_24.png", true, true},
	{"../Texture/MapTiles/Floor_25.png", true, false},

	{"../Texture/MapTiles/Grass_1.png", true, true},
	{"../Texture/MapTiles/Grass_2.png", true, true},
	{"../Texture/MapTiles/Grass_3.png", true, true},
	{"../Texture/MapTiles/Grass_4.png", true, true},
	{"../Texture/MapTiles/Grass_5.png", true, true},

	{"../Texture/MapTiles/Mac_1.png", false, false},
	{"../Texture/MapTiles/Mac_2.png", false, false},
	{"../Texture/MapTiles/Mac_3.png", false, false},
	{"../Texture/MapTiles/Mac_4.png", false, false},
	{"../Texture/MapTiles/Mac_5.png", false, false},
	{"../Texture/MapTiles/Mac_6.png", false, false},
	{"../Texture/MapTiles/Mac_7.png", false, false},
	{"../Texture/MapTiles/Mac_8.png", false, false},
	{"../Texture/MapTiles/Mac_9.png", false, false},
	{"../Texture/MapTiles/Mac_10.png", false, false},
	{"../Texture/MapTiles/Mac_11.png", false, false},
	{"../Texture/MapTiles/Mac_12.png", false, false},
	{"../Texture/MapTiles/Mac_13.png", false, false},
	{"../Texture/MapTiles/Mac_14.png", false, false},
	{"../Texture/MapTiles/Mac_15.png", false, false},

	{"../Texture/MapTiles/Map_1.png", false, false},
	{"../Texture/MapTiles/Map_2.png", true, true},
	{"../Texture/MapTiles/Map_3.png", true, true},
	{"../Texture/MapTiles/Map_4.png", false, false},
	{"../Texture/MapTiles/Map_5.png", false, false},
	{"../Texture/MapTiles/Map_6.png", false, false},
	{"../Texture/MapTiles/Map_7.png", false, false},
	{"../Texture/MapTiles/Map_8.png", false, false},
	{"../Texture/MapTiles/Map_9.png", false, false},
	{"../Texture/MapTiles/Map_10.png", true, true},
	{"../Texture/MapTiles/Map_11.png", false, false},
	{"../Texture/MapTiles/Map_12.png", false, false},
	{"../Texture/MapTiles/Map_13.png", false, false},
	{"../Texture/MapTiles/Map_14.png", false, false},
	{"../Texture/MapTiles/Map_15.png", false, false},
	{"../Texture/MapTiles/Map_16.png", false, false},
	{"../Texture/MapTiles/Map_17.png", false, false},
	{"../Texture/MapTiles/Map_18.png", false, false},
	{"../Texture/MapTiles/Map_19.png", false, false},
	{"../Texture/MapTiles/Map_20.png", false, false},
	{"../Texture/MapTiles/Map_21.png", false, false},

	{"../Texture/MapTiles/Rock_1.png", false, false},
	{"../Texture/MapTiles/Rock_2.png", true, false},

	{"../Texture/MapTiles/Sand_1.png", true, true},
	{"../Texture/MapTiles/Sand_2.png", true, true},
	{"../Texture/MapTiles/Sand_3.png", true, true},
	{"../Texture/MapTiles/Sand_4.png", false, false},

	{"../Texture/MapTiles/Sky_1.png", true, true},
	{"../Texture/MapTiles/Sky_2.png", true, false},

	{"../Texture/MapTiles/Tree_1.png", false, false},
	{"../Texture/MapTiles/Tree_2.png", true, false},

	{"../Texture/MapTiles/Wall_1.png", false, false},
	{"../Texture/MapTiles/Wall_2.png", false, false},
	{"../Texture/MapTiles/Wall_3.png", false, false},
	{"../Texture/MapTiles/Wall_4.png", false, false},
	{"../Texture/MapTiles/Wall_5.png", false, false},
	{"../Texture/MapTiles/Wall_6.png", false, false},
	{"../Texture/MapTiles/Wall_7.png", false, false},
	{"../Texture/MapTiles/Wall_8.png", false, false},
	{"../Texture/MapTiles/Wall_9.png", false, false},
	{"../Texture/MapTiles/Wall_10.png", false, false},
	{"../Texture/MapTiles/Wall_11.png", false, false},
	{"../Texture/MapTiles/Wall_12.png", false, false},
	{"../Texture/MapTiles/Wall_13.png", false, false},
	{"../Texture/MapTiles/Wall_14.png", false, false},
	{"../Texture/MapTiles/Wall_15.png", false, false},
	{"../Texture/MapTiles/Wall_16.png", false, false},
	{"../Texture/MapTiles/Wall_17.png", false, false},
	{"../Texture/MapTiles/Wall_18.png", false, false},
	{"../Texture/MapTiles/Wall_19.png", false, false},
	{"../Texture/MapTiles/Wall_20.png", false, false},
	{"../Texture/MapTiles/Wall_21.png", false, false},
	{"../Texture/MapTiles/Wall_22.png", false, false},
	{"../Texture/MapTiles/Wall_23.png", false, false},
	{"../Texture/MapTiles/Wall_24.png", false, false},
	{"../Texture/MapTiles/Wall_25.png", false, false},
	{"../Texture/MapTiles/Wall_26.png", false, false},
	{"../Texture/MapTiles/Wall_27.png", false, false},
	{"../Texture/MapTiles/Wall_28.png", false, false},
	{"../Texture/MapTiles/Wall_29.png", false, false},
	{"../Texture/MapTiles/Wall_30.png", false, false},
	{"../Texture/MapTiles/Wall_31.png", false, false},
	{"../Texture/MapTiles/Wall_32.png", false, false},
	{"../Texture/MapTiles/Wall_33.png", false, false},
	{"../Texture/MapTiles/Wall_34.png", false, false},
	{"../Texture/MapTiles/Wall_35.png", false, false},
	{"../Texture/MapTiles/Wall_36.png", false, false},
	{"../Texture/MapTiles/Wall_37.png", false, false},
	{"../Texture/MapTiles/Wall_38.png", false, false},
	{"../Texture/MapTiles/Wall_39.png", false, false},
	{"../Texture/MapTiles/Wall_40.png", false, false},
	{"../Texture/MapTiles/Wall_41.png", false, false},
	{"../Texture/MapTiles/Wall_42.png", false, false},
	{"../Texture/MapTiles/Wall_43.png", false, false},
	{"../Texture/MapTiles/Wall_44.png", false, false},
	{"../Texture/MapTiles/Wall_45.png", false, false},
	{"../Texture/MapTiles/Wall_46.png", false, false},
	{"../Texture/MapTiles/Wall_47.png", false, false},
	{"../Texture/MapTiles/Wall_48.png", false, false},
	{"../Texture/MapTiles/Wall_49.png", false, false},
	{"../Texture/MapTiles/Wall_50.png", false, false},
	{"../Texture/MapTiles/Wall_51.png", false, false},
	{"../Texture/MapTiles/Wall_52.png", false, false},
	{"../Texture/MapTiles/Wall_53.png", false, false},
	{"../Texture/MapTiles/Wall_54.png", false, false},
	{"../Texture/MapTiles/Wall_55.png", false, false},
	{"../Texture/MapTiles/Wall_56.png", false, false},
	{"../Texture/MapTiles/Wall_57.png", false, false},
	{"../Texture/MapTiles/Wall_58.png", false, false},
	{"../Texture/MapTiles/Wall_59.png", false, false},
	{"../Texture/MapTiles/Wall_60.png", false, false},
	{"../Texture/MapTiles/Wall_61.png", false, false},
	{"../Texture/MapTiles/Wall_62.png", false, false},
	{"../Texture/MapTiles/Wall_63.png", false, false},
	{"../Texture/MapTiles/Wall_64.png", false, false},
	{"../Texture/MapTiles/Wall_65.png", false, false},
	{"../Texture/MapTiles/Wall_66.png", false, false},
	{"../Texture/MapTiles/Wall_67.png", false, false},
	{"../Texture/MapTiles/Wall_68.png", false, false},
	{"../Texture/MapTiles/Wall_69.png", false, false},
	{"../Texture/MapTiles/Wall_70.png", false, false},
	{"../Texture/MapTiles/Wall_71.png", false, false},
	{"../Texture/MapTiles/Wall_72.png", false, false},
	{"../Texture/MapTiles/Wall_73.png", false, false},
	{"../Texture/MapTiles/Wall_74.png", false, false},
	{"../Texture/MapTiles/Wall_75.png", false, false},
	{"../Texture/MapTiles/Wall_76.png", false, false},
	{"../Texture/MapTiles/Wall_77.png", false, false},
	{"../Texture/MapTiles/Wall_78.png", false, false},
	{"../Texture/MapTiles/Wall_79.png", false, false},
	{"../Texture/MapTiles/Wall_80.png", false, false},
	{"../Texture/MapTiles/Wall_81.png", false, false},
	{"../Texture/MapTiles/Wall_82.png", false, false},
	{"../Texture/MapTiles/Wall_83.png", false, false},
	{"../Texture/MapTiles/Wall_84.png", false, false},
	{"../Texture/MapTiles/Wall_85.png", false, false},
	{"../Texture/MapTiles/Wall_86.png", false, false},
	{"../Texture/MapTiles/Wall_87.png", false, false},
	{"../Texture/MapTiles/Wall_88.png", false, false},

	{"../Texture/MapTiles/Water_1.png", false, false},
	{"../Texture/MapTiles/Water_2.png", false, false},

	{"../Texture/MapTiles/Append_1.png", false, false},
	{"../Texture/MapTiles/Append_2.png", false, false},
	{"../Texture/MapTiles/Append_3.png", true, true},
	{"../Texture/MapTiles/Append_4.png", true, false}
};

#endif